/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  $(document).ready(function () {

      $.ajax('https://query.yahooapis.com/v1/public/yql', {
        method: 'GET',
        data: {
          q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="Taipei")',
          format: 'json'
        },

        success: function (data) {
		 var weatherInfo = data.query.results.channel;
         
		console.log(weatherInfo);

	             $('.temperature').text(temp_F_to_C(weatherInfo.item.condition.temp));

	             $('.condition').text(weatherInfo.item.forecast[0].date);



	             for (i = 1; i < 4; i++){ 
				 	$('."range"+i').text(temp_F_to_C(weatherInfo.item.forecast[i].low) +'-'+ temp_F_to_C(weatherInfo.item.forecast[i].high) 
				 }


				 for (i = 1; i < 4; i++){ 
				 	$('."d"+i').text(weatherInfo.item.forecast[i].date);
				 }


				 for (i = 0; i < 4; i++){ 
				 	if(weatherInfo.item.forecast[i].text==="Heavy Rain"||
				  	   weatherInfo.item.forecast[i].text==="Rain"){

				 		skycons.set("icon"+i,Skycons.SLEET);

				  	}else if(weatherInfo.item.forecast[i].text==="PM Thunderstorms"||
				  			 weatherInfo.item.forecast[i].text==="Heavy Thunderstorms"||
				  			 weatherInfo.item.forecast[i].text==="Thunderstorms"||
				  			 weatherInfo.item.forecast[i].text==="Thundershowers/Wind"||
				  			 weatherInfo.item.forecast[i].text==="Showers"||
				  			 weatherInfo.item.forecast[i].text==="AM Showers"){
				 	  			
				 	  			skycons.set("icon"+i,Skycons.RAIN);

				  	}else if(weatherInfo.item.forecast[i].text==="Clear"||
				  			 weatherInfo.item.forecast[i].text==="Sunny"){

				 	  		 	skycons.set("icon"+i,Skycons.CLEAR_DAY);

				  	}else if(weatherInfo.item.forecast[i].text==="Partly Cloudy"||
				  			 weatherInfo.item.forecast[i].text==="AM Clouds/PM Sun"){
				 	  			
				 	  			skycons.set("icon"+i,Skycons.CLOUDY);
				  }
			     }
				 skycons.play();
		
		
		}
      });

  });


   
$('#dropdown li').on('click', function(){
    //alert($(this).text());
	$('.dropdown-toggle').html($(this).text()+'  <span class="caret"></span>');

	var city=$(this).text();
	       $.ajax('https://query.yahooapis.com/v1/public/yql', {
	         method: 'GET',
	         data: {
	           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
	           format: 'json'
	         },
	         success: function (data) {

				 var weatherInfo = data.query.results.channel;
				 console.log(weatherInfo);

	             $('.temperature').text(temp_F_to_C(weatherInfo.condition.temp));

	             $('.condition').text(weatherInfo.item.forecast[0].date);

	             $('.range_1').text(temp_F_to_C(weatherInfo.item.forecast[i].low) +'-'+ temp_F_to_C(weatherInfo.item.forecast[i].high)
	              
	             for (i = 1; i < 4; i++){ 
				 	$('."range_"+i').text(temp_F_to_C(weatherInfo.item.forecast[i].low) +'-'+ temp_F_to_C(weatherInfo.item.forecast[i].high) 
				 }


				 for (i = 1; i < 4; i++){ 
				 	$('."d_"+i').text(weatherInfo.forecast[i].date);
				 }


				 for (i = 0; i < 4; i++){ 
				 	if(weatherInfo.item.forecast[i].text==="Heavy Rain"||
				  	   weatherInfo.item.forecast[i].text==="Rain"){

				 		skycons.set("icon"+i,Skycons.SLEET);

				  	}else if(weatherInfo.item.forecast[i].text==="PM Thunderstorms"||
				  			 weatherInfo.item.forecast[i].text==="Heavy Thunderstorms"||
				  			 weatherInfo.item.forecast[i].text==="Thunderstorms"||
				  			 weatherInfo.item.forecast[i].text==="Thundershowers/Wind"||
				  			 weatherInfo.item.forecast[i].text==="Showers"||
				  			 weatherInfo.item.forecast[i].text==="AM Showers"){
				 	  			
				 	  			skycons.set("icon"+i,Skycons.RAIN);

				  	}else if(weatherInfo.item.forecast[i].text==="Clear"||
				  			 weatherInfo.item.forecast[i].text==="Sunny"){

				 	  		 	skycons.set("icon"+i,Skycons.CLEAR_DAY);

				  	}else if(weatherInfo.item.forecast[i].text==="Partly Cloudy"||
				  			 weatherInfo.item.forecast[i].text==="AM Clouds/PM Sun"){
				 	  			
				 	  			skycons.set("icon"+i,Skycons.CLOUDY);
				  }
			     }
				 skycons.play();
	         }
	       });
});


function temp_F_to_C(temp_F){
  var temp_C = formatFloat((temp_F-32)*5/9);
  return temp_C;
};
